### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by HasnatKazi**
Accept this, please.

### CODE REVIEW

**Comment by vyomcoding** [comment]
maybe

**Comment by vyomcoding** [comment]
idk

**Comment by HasnatKazi** [comment]
pretty please??

**Comment by vyomcoding** [comment]
ok fine

**Comment by vyomcoding** [comment]
there is an error on line 5

it also needs to be more exciting

**Comment by vyomcoding** [comment]
ok

**Comment by vyomcoding** [comment]
this is a bit better

**Comment by vyomcoding** [comment]
i will *merge* this now

**Pull request merged**
